"""empty message

Revision ID: 9cf64e264921
Revises: 
Create Date: 2020-09-16 18:26:41.468274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf64e264921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.Float(), nullable=False),
    sa.Column('dataNascimento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idPessoa')
    )
    op.create_table('contas',
    sa.Column('idConta', sa.Integer(), nullable=False),
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('limiteSaqueDiario', sa.Float(), nullable=False),
    sa.Column('flagAtivo', sa.Boolean(), nullable=False),
    sa.Column('tipoConta', sa.Integer(), nullable=False),
    sa.Column('dataCriacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoas.idPessoa'], ),
    sa.PrimaryKeyConstraint('idConta')
    )
    op.create_table('transacoes',
    sa.Column('idTransacao', sa.Integer(), nullable=False),
    sa.Column('idconta', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dataTransacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idconta'], ['contas.idConta'], ),
    sa.PrimaryKeyConstraint('idTransacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('contas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
